// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD-I4vJjAeDFtbzq7ZMYBs3bx3Uzig5VI',
    appId: '1:59523096509:web:b933af8fcfa136168bbcd4',
    messagingSenderId: '59523096509',
    projectId: 'task-management-apps-cc8d9',
    authDomain: 'task-management-apps-cc8d9.firebaseapp.com',
    storageBucket: 'task-management-apps-cc8d9.appspot.com',
    measurementId: 'G-8JED5620KR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhuYFCL97z95capAMqugRWdsgE_R6I31M',
    appId: '1:59523096509:android:5beaf3deb8637efc8bbcd4',
    messagingSenderId: '59523096509',
    projectId: 'task-management-apps-cc8d9',
    storageBucket: 'task-management-apps-cc8d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDc0SpcFhnhf-xr10Oh7q9KSVAdvFAops',
    appId: '1:59523096509:ios:c56d24932ae2e9ad8bbcd4',
    messagingSenderId: '59523096509',
    projectId: 'task-management-apps-cc8d9',
    storageBucket: 'task-management-apps-cc8d9.appspot.com',
    androidClientId: '59523096509-nq22cii4cdpg5snd26ilpsqe0g5elsre.apps.googleusercontent.com',
    iosClientId: '59523096509-jg50mu578pn7frgrk0tv6ijdjd6dhl65.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDc0SpcFhnhf-xr10Oh7q9KSVAdvFAops',
    appId: '1:59523096509:ios:c56d24932ae2e9ad8bbcd4',
    messagingSenderId: '59523096509',
    projectId: 'task-management-apps-cc8d9',
    storageBucket: 'task-management-apps-cc8d9.appspot.com',
    androidClientId: '59523096509-nq22cii4cdpg5snd26ilpsqe0g5elsre.apps.googleusercontent.com',
    iosClientId: '59523096509-jg50mu578pn7frgrk0tv6ijdjd6dhl65.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagementApp',
  );
}
